### ISSUE TITLE
Reference pollenprognos-card in the README?

### ISSUE THREAD

**Issue by krissen** [danishru/silam_pollen#8]
Hi,

I'm the developer of [pollenprognos-card](https://github.com/krissen/pollenprognos-card), a custom card showing pollen information. I've just ([v2.3.0](https://github.com/krissen/pollenprognos-card/releases/tag/v2.3.0)) added support for the `silam_pollen` integration.

If you find it apt, it could perhaps be mentioned in the README of `silam_pollen` as an option for showing the sensor data?

Should you wish, I can make a PR with such a change.

Here are some examples:

<img width="477" alt="Image" src="https://github.com/user-attachments/assets/204fb79f-b4a8-47e1-b60a-a2fbaa427587" />
<img width="488" alt="Image" src="https://github.com/user-attachments/assets/8f70f4e0-095a-42a9-b7dc-b39ef2366f4b" />
<img width="488" alt="Image" src="https://github.com/user-attachments/assets/1b501931-df5c-448f-9ae3-b4dedef5ea24" />
<img width="475" alt="Image" src="https://github.com/user-attachments/assets/b28cce44-8b38-4d2e-b684-237cdfde69f2" />
<img width="448" alt="Image" src="https://github.com/user-attachments/assets/4b61d45b-1f68-4461-87ac-d4ff5a455b23" />
<img width="469" alt="Image" src="https://github.com/user-attachments/assets/76165c4d-d040-4336-84d7-a6250dd2f49b" />
<img width="472" alt="Image" src="https://github.com/user-attachments/assets/4490cc65-4d63-40b0-9cde-a608c0dfdeff" />

**Comment by danishru** [comment]
Thanks a lot, [@krissen](https://github.com/krissen) — this is **awesome!** I really appreciate that you added `silam_pollen` support to `pollenprognos-card`.

I’ve tested the card and found one issue: **there’s currently no way to choose a location**.  
Your screenshots show different cities, but in my setup the card displays only a single location and it’s unclear how that one is selected. I’ll open an issue in your repo so we can track it.

#### Integration capabilities

* `silam_pollen` exposes its forecast via the **native Weather entity** in Home Assistant.  
* In the integration options you can set the forecast horizon **from 36 to 120 hours** (up to 5 days).  
* The integration provides two forecast datasets:  
  * **twice daily** forecast.
  * an **hourly** forecast.  
* Both are accessible via the `weather.get_forecasts` service.  
* 👉 _Usage examples in the README_: <https://github.com/danishru/silam_pollen?tab=readme-ov-file#usage>

If your card could display those forecasts, it would become a real *killer feature*. That’s on my roadmap too, but it requires digging into how the built-in HA weather-forecast card works and will take some effort to implement.

I’m happy to reference `pollenprognos-card` in my README once the location-selection bug is fixed. Feel free to open a PR and I’ll adjust the wording if needed.

Thanks again for the great work! 🚀

**Comment by krissen** [comment]
> Oh! And if you have suggestions for better levels (none/low etc) for the respective particles, I'm all ears! Currently I set it thus ([adapters/silam.js](https://github.com/krissen/pollenprognos-card/blob/master/src/adapters/silam.js#L53-L61)):

```yaml
  const SILAM_THRESHOLDS = {
    birch: [0, 1, 10, 50, 100, 200, 400],
    grass: [0, 1, 10, 30, 50, 100, 200],
    hazel: [0, 1, 5, 20, 50, 100, 200],
    alder: [0, 1, 5, 20, 50, 100, 200],
    ragweed: [0, 1, 3, 10, 30, 50, 100],
    mugwort: [0, 1, 5, 15, 30, 50, 100],
    olive: [0, 1, 3, 10, 20, 50, 100],
  };
```

In the README, you reference "threshold levels from Mikhail Sofiev’s table ([link](https://www.researchgate.net/profile/Mikhail-Sofiev))." Could you possibly link directly to the table, or at least in what publication? I tried to find it, but there is *a lot* to sift through, and from the titles I couldn't discern where said table might be.

**Comment by danishru** [comment]
> > Oh! And if you have suggestions for better levels (none/low etc) for the respective particles, I'm all ears! Currently I set it thus ([adapters/silam.js](https://github.com/krissen/pollenprognos-card/blob/master/src/adapters/silam.js#L53-L61)):
> 
>   const SILAM_THRESHOLDS = {
>     birch: [0, 1, 10, 50, 100, 200, 400],
>     grass: [0, 1, 10, 30, 50, 100, 200],
>     hazel: [0, 1, 5, 20, 50, 100, 200],
>     alder: [0, 1, 5, 20, 50, 100, 200],
>     ragweed: [0, 1, 3, 10, 30, 50, 100],
>     mugwort: [0, 1, 5, 15, 30, 50, 100],
>     olive: [0, 1, 3, 10, 20, 50, 100],
>   };
> In the README, you reference "threshold levels from Mikhail Sofiev’s table ([link](https://www.researchgate.net/profile/Mikhail-Sofiev))." Could you possibly link directly to the table, or at least in what publication? I tried to find it, but there is _a lot_ to sift through, and from the titles I couldn't discern where said table might be.

Hi there! 👋
I’ve opened a Pull Request that updates the thresholds with values taken straight from the official FMI legend used on the SILAM map:

PR: Update thresholds to match FMI colour-scale when using silam_pollen integration
https://github.com/krissen/pollenprognos-card/pull/41

**Comment by krissen** [comment]
Excellent, thank you!

I've made preliminary support for showing hourly data, using forecast. _However,_ I've yet to see `forecast`attribute in the silam pollen weather entities. Haven't delved into the code to see whether support is built in or not.

It is feasible to make the card do service calls to fetch the forecast, but I'm worried that would lead to unnecessary traffic. If the weather forecast would have a forecast attribute like:
```yaml
attributes:
  temperature_unit: '°C'
  ...
  forecast:
    - datetime: '2025-07-01T09:00:00+00:00'
      condition: high
      native_temperature_unit: °C
      pollen_index: 4
      temperature: 33.6
      pollen_alder: 0
      pollen_birch: 0
      pollen_grass: 55
      pollen_hazel: 0
      pollen_mugwort: 0
      pollen_olive: 0
      pollen_ragweed: 0
    - datetime: ...
      ...
```
then that could be read directly, without service calls? Not sure here; let me know what you think.
